### ISSUE TITLE
Algorithm failed with error Cannot run model(plugin installed qgis)

### ISSUE THREAD

**Issue by samk8028** [3liz/py-qgis-wps#60]
Hello, guys!
I have developed a relatively complex routing model that uses plugin Least_cost_path , but I encounter the following errors when using this plugin. What is the solution?

`wps-1    | 2024-12-16 15:03:00,704      [26]    INFO    Starting task d790bcba:model:LCP_5-new
wps-1    | 2024-12-16 15:03:00,707      [26]    DEBUG   Resolving 'file' protocol
wps-1    | 2024-12-16 15:03:00,707      [26]    DEBUG   Reading Qgis project /projects/routing.qgs
wps-1    | 2024-12-16 15:03:00,899      [26]    DEBUG   Handling destination layer: buffer_area, details name: None
wps-1    | 2024-12-16 15:03:00,899      [26]    DEBUG   Handling destination layer: distance_between_tow_points, details name: None
wps-1    | 2024-12-16 15:03:00,899      [26]    DEBUG   Handling destination layer: waypoints, details name: None
wps-1    | 2024-12-16 15:03:00,901      [26]    CRITICAL        Traceback (most recent call last):
wps-1    |   File "/py-qgis-wps/pyqgiswps/executors/processingprocess.py", line 280, in run_processing_algorithm
wps-1    |     results, ok = alg.run(
wps-1    |                   ^^^^^^^^
wps-1    | _core.QgsProcessingException: Cannot run model, the following algorithms are not available on this system: Cost distance analysis:Least Cost Path_1
wps-1    | 
wps-1    | 2024-12-16 15:03:00,901      [26]    INFO    model:LCP_5-new:d790bcba memory: start=191.496Mb end=208.496Mb delta=17.000Mb duration: 0.197s
wps-1    | 2024-12-16 15:03:00,902      [26]    ERROR   Worker exception: >>>>>>>>>>
wps-1    | Traceback (most recent call last):
wps-1    |   File "/py-qgis-wps/pyqgiswps/poolserver/worker.py", line 90, in worker_handler
wps-1    |     result = (True, func(*args, **kwargs))
wps-1    |                     ^^^^^^^^^^^^^^^^^^^^^
wps-1    |   File "/py-qgis-wps/pyqgiswps/executors/processingexecutor.py", line 344, in _run_process
wps-1    |     handler(wps_request, wps_response)
wps-1    |   File "/py-qgis-wps/pyqgiswps/executors/processingprocess.py", line 438, in _handler
wps-1    |     run_algorithm(
wps-1    |   File "/py-qgis-wps/pyqgiswps/executors/processingprocess.py", line 309, in run_algorithm
wps-1    |     results = run_processing_algorithm(
wps-1    |               ^^^^^^^^^^^^^^^^^^^^^^^^^
wps-1    |   File "/py-qgis-wps/pyqgiswps/executors/processingprocess.py", line 291, in run_processing_algorithm
wps-1    |     raise ProcessException(f"Algorithm failed with error {err}") from None
wps-1    | pyqgiswps.exceptions.ProcessException: Algorithm failed with error Cannot run model, the following algorithms are not available on this system: Cost distance analysis:Least Cost Path_1
wps-1    | <<<<<<<<<<
wps-1    | 2024-12-16 15:03:00,902      [26]    DEBUG   SND b'\xd7\x97\xfc^\xbb\xbe\x11\xef\x89\x91y\xc3\xce{\x9fi'
wps-1    | 2024-12-16 15:03:00,902      [26]    INFO    Terminating Worker
wps-1    | 2024-12-16 15:03:00,903      [1]     DEBUG   Receveid b'\xd7\x97\xfc^\xbb\xbe\x11\xef\x89\x91y\xc3\xce{\x9fi', success False
`

**Comment by dmarteau** [comment]
Apparently you try to run a algorithm that depends on another which is not found by the service, you must install the missing processing algs server side.

**Comment by AbdulsalamAmin** [comment]
Thank you. However, I have a few questions:

1. Is it possible to run the plugins installed in QGIS using this service? If yes, how can they be executed, and what is the configuration process?


2. What exactly is meant by "plugins"? Are you referring to the plugins located in the /usr/share/qgis directory on Linux, or something else?


3. Should the GRASS and OTB providers be installed as part of QGIS, or do they need to be set up externally?

**Comment by dmarteau** [comment]
> Thank you. However, I have a few questions:
> 
>     1. Is it possible to run the plugins installed in QGIS using this service? If yes, how can they be executed, and what is the configuration process?

No, QgGIS is a desktop softare and py-qgis-wps is a server.  so they are meant to be run on separate environments.
You may use any QGIS WPS plugin  but will have to install it by hand on the server and make sure that it is properly setup for running in a headless mode.

>     2. What exactly is meant by "plugins"? Are you referring to the plugins located in the /usr/share/qgis directory on Linux, or something else?

QGIS plugins as defined in https://plugins.qgis.org/

> 
>     3. Should the GRASS and OTB providers be installed as part of QGIS, or do they need to be set up externally?

GRASS and OTB are external providers.

**Comment by AbdulsalamAmin** [comment]
> > Thank you. However, I have a few questions:
> > 
> >     1. Is it possible to run the plugins installed in QGIS using this service? If yes, how can they be executed, and what is the configuration process?
> 
> No, QgGIS is a desktop softare and py-qgis-wps is a server.  so they are meant to be run on separate environments.
> You may use any QGIS WPS plugin  but will have to install it by hand on the server and make sure that it is properly setup for running in a headless mode.
> 
> >     2. What exactly is meant by "plugins"? Are you referring to the plugins located in the /usr/share/qgis directory on Linux, or something else?
> 
> QGIS plugins as defined in https://plugins.qgis.org/
> 
> > 
> >     3. Should the GRASS and OTB providers be installed as part of QGIS, or do they need to be set up externally?
> 
> GRASS and OTB are external providers.
> 
> 

Thank you very much for your prompt response. Both QGIS and pywps are on the same system, but I am running pywps inside Docker. How can I manually install a plugin and make it available to pywps?
