### ISSUE TITLE
pyyaml missing in requirements.txt ?

### ISSUE THREAD

**Issue by tloubrieu-jpl** [3liz/py-qgis-wps#7]
Hello,

I am trying your server (I am interested in re-using your WPS tornado handler).

Just as a feedback so far. When I installed as follow:
pip install https://github.com/3liz/py-qgis-wps/archive/1.4.1.tar.gz

then launched:
% wpsserver -h    
Failed to read manifest !: [Errno 2] No such file or directory: '/Users/loubrieu/PycharmProjects/incubator-sdap-nexus/qgis_wps/lib/python3.7/site-packages/pyqgiswps/build.manifest' 
Traceback (most recent call last):
  File "/Users/loubrieu/PycharmProjects/incubator-sdap-nexus/qgis_wps/bin/wpsserver", line 11, in <module>
    load_entry_point('py-qgis-wps==1.4.1', 'console_scripts', 'wpsserver')()
  File "/Users/loubrieu/PycharmProjects/incubator-sdap-nexus/qgis_wps/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/loubrieu/PycharmProjects/incubator-sdap-nexus/qgis_wps/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/Users/loubrieu/PycharmProjects/incubator-sdap-nexus/qgis_wps/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/Users/loubrieu/PycharmProjects/incubator-sdap-nexus/qgis_wps/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/loubrieu/PycharmProjects/incubator-sdap-nexus/qgis_wps/lib/python3.7/site-packages/pyqgiswps/wpsserver.py", line 17, in <module>
    from .runtime import run_server
  File "/Users/loubrieu/PycharmProjects/incubator-sdap-nexus/qgis_wps/lib/python3.7/site-packages/pyqgiswps/runtime.py", line 27, in <module>
    from .handlers import (RootHandler, WPSHandler, StoreHandler, StatusHandler, 
  File "/Users/loubrieu/PycharmProjects/incubator-sdap-nexus/qgis_wps/lib/python3.7/site-packages/pyqgiswps/handlers/__init__.py", line 11, in <module>
    from .wpshandler import WPSHandler, StatusHandler
  File "/Users/loubrieu/PycharmProjects/incubator-sdap-nexus/qgis_wps/lib/python3.7/site-packages/pyqgiswps/handlers/wpshandler.py", line 22, in <module>
    from ..accesspolicy import new_access_policy
  File "/Users/loubrieu/PycharmProjects/incubator-sdap-nexus/qgis_wps/lib/python3.7/site-packages/pyqgiswps/accesspolicy.py", line 5, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

I've installed pyyaml and the error disappeared.

I guess if pyyaml is added in the requirements.txt then the package will include the dependency.

Thanks for doing this development, I will go on looking at it.

**Comment by dmarteau** [comment]
Fixed in d8372bf
